print('printing absoluste function with input as integers')
print()
a = abs(5)
b = abs(-5)
c = abs(+5)
print(a,b,c)

print('printing absoluste function with input as float')
print()
a = abs(5.0)
b = abs(-5.0)
c = abs(+5.0)
print(a,b,c)

print('printing a complex number')
print()
magnitude = abs(3+4j)
print(magnitude)
print(type(magnitude))